### ISSUE TITLE
Library not usable, using current PSL1GHT toolchain

### ISSUE THREAD

**Issue by crystalct** [gzorin/RSXGL#13]
Since July 2020 it's not compilable, but even adjusting compiling issues, eglCreateWindowSurface fail caused by gcmInitBody that keep to NULL _rsx_gcm_context although it returns a value equal to zero.
@gzorin and @kakaroto  please spent few time to adjust this library to be usefull. Thanks.

**Comment by kakaroto** [comment]
> @gzorin and @kakaroto please spent few time to adjust this library to be usefull. Thanks.

Sorry, I have no time or interest in looking at or maintaining this 10 year old project that I have long ago moved on from.

**Comment by crystalct** [comment]
I understand. Probably all I need is just some advice.
I fond where is the problem that is raised using g++ 7.2  (obviously not present in the past with g++ 4.x).
There many structures/classes: sampler_t, attribs_t, memory_arena_t etc etc, with inside a storage_type.
For example attribs_t (https://github.com/gzorin/RSXGL/blob/master/src/library/attribs.h)
It has:
```
typedef bindable_gl_object< sampler_t, RSXGL_MAX_SAMPLERS, RSXGL_MAX_COMBINED_TEXTURE_IMAGE_UNITS > gl_object_type;
typedef typename gl_object_type::storage_type storage_type;
```
any attemp of creating a variable of type `attribs_t::storage_type` a segmentation fault is raised.
`attribs_t::storage_type attrib_x(0,0);` or `attribs_t::storage_type *attrib_x = new attribs_t::storage_type();` or `attribs_t::storage_type attrib_x;` all raised a segmentation falt
Even
```
typedef bindable_gl_object< attribs_t, RSXGL_MAX_VERTEX_ARRAYS, RSXGL_MAX_VERTEX_ARRAY_TARGETS, 1 > gl_object_type;
gl_object_type::storage_type sto_attribs_t; 
```
raises a segmentattion fault.

Do you have an advice for me?

**Comment by mirh** [comment]
Trying to bisect is never wrong. 
Even though the further behind in time you go, the more it's a PITA (but you can find all versions going back to 4.3 in a somewhat buildable state on the AUR)

**Comment by crystalct** [comment]
Meanwhile i found a first step to go ahead:
```
#ifdef NDEBUG
# define rsxgl_assert(__e) ((void)0)
#else
# define rsxgl_assert(__e) ((__e) ? (void)0 : __rsxgl_assert_func (__FILE__, __LINE__, \
							     __RSXGL_ASSERT_FUNC, #__e))

# ifndef __RSXGL_ASSERT_FUNC
  /* Use g++'s demangled names in C++.  */
#  if defined __cplusplus && defined __GNUC__
#   define __RSXGL_ASSERT_FUNC __PRETTY_FUNCTION__

  /* C99 requires the use of __func__.  */
#  elif __STDC_VERSION__ >= 199901L
#   define __RSXGL_ASSERT_FUNC __func__

  /* Older versions of gcc don't have __func__ but can use __FUNCTION__.  */
#  elif __GNUC__ >= 2
#   define __RSXGL_ASSERT_FUNC __FUNCTION__

  /* failed to detect __func__ support.  */
#  else
#   define __RSXGL_ASSERT_FUNC ((char *) 0)
#  endif
# endif /* !__RSXGL_ASSERT_FUNC */
#endif /* !NDEBUG */
```
If i define NDEBUG that structs/classes can be instantiated without causing segmentation faults.

**Comment by crystalct** [comment]
Solved:
https://www.psx-place.com/threads/rsxgl-status.34031/
